### ISSUE TITLE
Expanding Square Pattern

### ISSUE THREAD

**Issue by 8eecf0d2** [em/svg2gcode#2]
After finally getting Cairo installed everytime I put an svg through, it just gives gcode for a square pattern (small square, larger bounding square, repeat)..

This is my command

`svg2gcode -t 3 -c 4 -d 3 -D 1 /Users/brod/Desktop/test.svg`

Any ideas?

**Comment by 8eecf0d2** [comment]
I have been able to get the svg2gcode.js from the gcode-simulator to work flawlessly, are they similar?

**Comment by em** [comment]
I'm afk now but I'll check it out in a few hours.

Also - cairo should not be required. I or canvg must be mistakenly requiring node-canvas as a dependency. I'll check into that too.

**Comment by 8eecf0d2** [comment]
Thanks.

Just checked, yeah the tree is Svg2gcode > Canvg > Canvas > Cairo

**Comment by em** [comment]
Can you share the svg with me so I can try it myself?

**Comment by 8eecf0d2** [comment]
sure, theres an inkscape and adobe illustrator version.

https://gist.github.com/brod/f6ec0ba6805eebbd82df

**Comment by em** [comment]
Ah. Looks like canvg handles fill="none" by calling fill() with ctx.fillStyle="rgba(0,0,0,0)"

I can fix this in Gcanvas by simply ignoring any 0 alpha fill or stroke. Thanks for finding this!

**Comment by em** [comment]
Try reinstalling svg2gcode and try it.

What are you using for simulation? All of the simulators out there I've seen are for windows, or just don't work. I'm working on a simulator, but it doesn't support everything yet in that test. But the issue with things filling instead of stroking is definitely fixed.

Gcanvas has a built-in simulator which I've been using, but will be removing once the generic one is complete. That simulator cheats and doesn't do gcode parsing since it's implemented as a driver and gets a lot more information.

Removing that simulator from Gcanvas is also going to make it possible to drop browser support (which is only useful for the simulator) and then I can do system font parsing with freetype.

Sorry that you're trying out these projects while they are still rocky. I really appreciate other people using them and reporting these issues. Can't wait until we have a reliable set of unix utilities for rapid CNC machining purely on the command line with elegant pipelines.

**Comment by em** [comment]
svg2gcode -D 5 ~/Downloads/test_adobe_ai.svg | gsim

![screen shot 2014-06-23 at 12 34 37 pm](https://cloud.githubusercontent.com/assets/337595/3360585/5e77247c-faf4-11e3-9238-b1284f72eebf.png)

I have no good way to simulate the arcs ATM so they aren't in my simulation. Some time this week I should get this out.

**Comment by 8eecf0d2** [comment]
Ahk, understood. Glad to help

**Comment by 8eecf0d2** [comment]
Didn't see the last 2 comments, just tried that command on another computer with a fresh first time install of node and gcode-simulator threw an which I haven't seen before so I'm guessing I've just got a screw loose somewhere.

I'm using https://github.com/tmpvar/gcode-simulator which works quite well as a browser simulator.

Yes I'm also excited for these tools become a part workflow, it's such a hassle currently switching environments, using gui's etc.
If I can find that ascii 3d environment library I'll have a go at making a simulator using that, just to complete the command line experience.

Again, thanks for all your work on this! really great stuff

**Comment by em** [comment]
Found some time tonight to do some more work on my simulator. svg2gcode definitely generates proper gcode for everything in that test svg and the issues I am seeing are purely in my new simulator.

![image](https://cloud.githubusercontent.com/assets/337595/3368602/c570040a-fb76-11e3-8889-083aa667fa2a.png)

Still some problems w/ the B but that's definitely just the simulator. Path data is there, I'm just not rendering it. I'll close this.
